### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rizky92** [Rizky92/smc-internal-app#7]
- [x] Migrasikan semua menu untuk pakai sistem export excel yang baru
- [x] Pindahkan sistem export excel menjadi library tersendiri
- [x] ~Membuat sistem import dari excel~
- [x] ~Buat test (25%)~
- [x] #12
- [x] Pindahkan property/method berulang ke traits
- [x] Sistem transfer hak akses di custom report
- [x] Sistem transfer hak akses di khanza
- [x] Sistem manajemen hak akses SIMRS Khanza
- [x] Tracker SQL khusus Custom Report
- [x] ~Keuangan melihat titip faktur yang belum dibayar~
- [x] ~Membuat login superadmin sesuai dengan SIMRS Khanza~
- [x] Rujukan keluar ke RS (laporan statistik)
- [x] Stok obat ruangan sortir berdasarkan nama obat
- [x] Buat fitur sortir kolom table
- [x] #10
- [x] Resolve masalah select2 tidak ter-render setelah component terupdate/refresh
- [x] #11
- [x] manajemen user untuk dokter ditambahkan
- [x] Fitur copy data untuk daftar pasien ranap (dan mungkin yang lainnya untuk proses pengubahan data)
- [x] Rekap piutang pasien
- [x] #16
- [x] implementasi fitur sortir ke berbagai menu
- [x] Fitur copy row ~table~ data pasien rawat inap
- [x] Fitur impersonasi user
- [x] Laporan penyelesaian billing pasien di kasir
- [x] #34
- [x] #19
- [x] ~#20~
- [x] ~#21~
- [x] Resolve masalah transfer hak akses user karena adanya nik dengan spasi (alternatif #20 dan #21)
- [x] #54
- [x] #53
- [x] Improve filter
- [x] #22
- [x] #23
